# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\About.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(925, 641)
        self.DisplayLabel = DisplayLabel(Frame)
        self.DisplayLabel.setGeometry(QtCore.QRect(300, 280, 301, 91))
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.HyperlinkButton = HyperlinkButton(Frame)
        self.HyperlinkButton.setGeometry(QtCore.QRect(10, 590, 128, 31))
        self.HyperlinkButton.setUrl(QtCore.QUrl("https://github.com/VMTask/WaterBox"))
        self.HyperlinkButton.setObjectName("HyperlinkButton")
        self.SubtitleLabel = SubtitleLabel(Frame)
        self.SubtitleLabel.setGeometry(QtCore.QRect(340, 360, 211, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.StrongBodyLabel = StrongBodyLabel(Frame)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(390, 390, 181, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.HyperlinkButton_2 = HyperlinkButton(Frame)
        self.HyperlinkButton_2.setGeometry(QtCore.QRect(747, 590, 161, 31))
        self.HyperlinkButton_2.setUrl(QtCore.QUrl("https://icons8.com"))
        self.HyperlinkButton_2.setObjectName("HyperlinkButton_2")
        self.ElevatedCardWidget = ElevatedCardWidget(Frame)
        self.ElevatedCardWidget.setGeometry(QtCore.QRect(280, 120, 341, 171))
        self.ElevatedCardWidget.setObjectName("ElevatedCardWidget")
        self.label = QtWidgets.QLabel(self.ElevatedCardWidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 111, 111))
        self.label.setStyleSheet("QLabel {\n"
"        background-color: rgba(0, 0, 0, 5%); /* 这里是半透明黑色背景，最后一个值是 alpha 通道，控制透明度 */\n"
"        border: 2px solid rgba(255, 255, 255, 50%); /* 这里是半透明白色边框，同样调整 alpha 通道以控制透明度 */\n"
"        border-radius: 10px; /* 设置边框的圆角大小 */\n"
"        padding: 4px; /* 如果需要内部内容与边框保持一定距离可设置内边距 */\n"
"    }")
        self.label.setText("")
        self.label.setObjectName("label")
        self.IconWidget = IconWidget(self.ElevatedCardWidget)
        self.IconWidget.setGeometry(QtCore.QRect(120, 40, 91, 91))
        self.IconWidget.setStyleSheet("background-color: rgba(0, 0, 0, 10%);\n"
"border: 2px solid rgba(255, 255, 255, 50%);\n"
"border-radius: 10px;\n"
"padding: 4px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.IconWidget.setIcon(icon)
        self.IconWidget.setObjectName("IconWidget")
        self.ToolButton = ToolButton(Frame)
        self.ToolButton.setGeometry(QtCore.QRect(20, 10, 38, 32))
        self.ToolButton.setObjectName("ToolButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.DisplayLabel.setText(_translate("Frame", "WaterBox"))
        self.HyperlinkButton.setText(_translate("Frame", "Github"))
        self.SubtitleLabel.setText(_translate("Frame", "一个好用的ADB工具箱"))
        self.StrongBodyLabel.setText(_translate("Frame", "Alpha Build Version"))
        self.HyperlinkButton_2.setText(_translate("Frame", "图标来自icon8.com"))
from qfluentwidgets import DisplayLabel, ElevatedCardWidget, HyperlinkButton, IconWidget, StrongBodyLabel, SubtitleLabel, ToolButton
