# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\WaterBox\interface\ApplicationActivity.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(925, 641)
        self.PlainTextEdit = PlainTextEdit(Frame)
        self.PlainTextEdit.setGeometry(QtCore.QRect(460, 110, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PlainTextEdit.setFont(font)
        self.PlainTextEdit.setStyleSheet("PlainTextEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"}\n"
"")
        self.PlainTextEdit.setReadOnly(True)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.TitleLabel = TitleLabel(Frame)
        self.TitleLabel.setGeometry(QtCore.QRect(470, 60, 123, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.SimpleCardWidget = SimpleCardWidget(Frame)
        self.SimpleCardWidget.setGeometry(QtCore.QRect(30, 410, 861, 211))
        self.SimpleCardWidget.setStyleSheet("border-radius: 10px;border-style: outset;\n"
"border: 2px rgb(190, 206, 221);\n"
"background-color: rgb(223, 232, 245);")
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.IconWidget = IconWidget(self.SimpleCardWidget)
        self.IconWidget.setGeometry(QtCore.QRect(30, 50, 131, 111))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/unknown_package.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.IconWidget.setIcon(icon)
        self.IconWidget.setObjectName("IconWidget")
        self.SubtitleLabel = SubtitleLabel(self.SimpleCardWidget)
        self.SubtitleLabel.setGeometry(QtCore.QRect(180, 30, 201, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.SubtitleLabel_2 = SubtitleLabel(self.SimpleCardWidget)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(180, 90, 201, 28))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.SubtitleLabel_4 = SubtitleLabel(self.SimpleCardWidget)
        self.SubtitleLabel_4.setGeometry(QtCore.QRect(440, 30, 371, 28))
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.SubtitleLabel_5 = SubtitleLabel(self.SimpleCardWidget)
        self.SubtitleLabel_5.setGeometry(QtCore.QRect(440, 90, 231, 28))
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.SubtitleLabel_6 = SubtitleLabel(self.SimpleCardWidget)
        self.SubtitleLabel_6.setGeometry(QtCore.QRect(280, 140, 261, 28))
        self.SubtitleLabel_6.setObjectName("SubtitleLabel_6")
        self.PrimaryPushButton_2 = PrimaryPushButton(self.SimpleCardWidget)
        self.PrimaryPushButton_2.setGeometry(QtCore.QRect(690, 160, 153, 32))
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.SubtitleLabel_7 = SubtitleLabel(self.SimpleCardWidget)
        self.SubtitleLabel_7.setGeometry(QtCore.QRect(40, 170, 201, 28))
        self.SubtitleLabel_7.setObjectName("SubtitleLabel_7")
        self.TitleLabel_2 = TitleLabel(Frame)
        self.TitleLabel_2.setGeometry(QtCore.QRect(30, 60, 141, 38))
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.ElevatedCardWidget = ElevatedCardWidget(Frame)
        self.ElevatedCardWidget.setGeometry(QtCore.QRect(30, 110, 421, 271))
        self.ElevatedCardWidget.setStyleSheet("border-radius: 10px;border-style: outset;\n"
"border: 2px rgb(190, 206, 221);\n"
"background-color: rgb(223, 232, 245);")
        self.ElevatedCardWidget.setObjectName("ElevatedCardWidget")
        self.SubtitleLabel_3 = SubtitleLabel(self.ElevatedCardWidget)
        self.SubtitleLabel_3.setGeometry(QtCore.QRect(30, 30, 141, 41))
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.LineEdit = LineEdit(self.ElevatedCardWidget)
        self.LineEdit.setGeometry(QtCore.QRect(30, 80, 261, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.PushButton = PushButton(self.ElevatedCardWidget)
        self.PushButton.setGeometry(QtCore.QRect(300, 80, 102, 32))
        self.PushButton.setObjectName("PushButton")
        self.PrimaryPushButton = PrimaryPushButton(self.ElevatedCardWidget)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(100, 150, 221, 51))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.IndeterminateProgressBar = IndeterminateProgressBar(Frame)
        self.IndeterminateProgressBar.setEnabled(True)
        self.IndeterminateProgressBar.setGeometry(QtCore.QRect(60, 30, 811, 4))
        self.IndeterminateProgressBar.setObjectName("IndeterminateProgressBar")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.PlainTextEdit.setPlainText(_translate("Frame", "Waiting for start......"))
        self.TitleLabel.setText(_translate("Frame", "终端命令"))
        self.SubtitleLabel.setText(_translate("Frame", "应用名称: Unknown"))
        self.SubtitleLabel_2.setText(_translate("Frame", "应用版本: Unknown"))
        self.SubtitleLabel_4.setText(_translate("Frame", "应用包名: Unknown"))
        self.SubtitleLabel_5.setText(_translate("Frame", "应用minSDK: Unknown"))
        self.SubtitleLabel_6.setText(_translate("Frame", "应用targetSDK: Unknown"))
        self.PrimaryPushButton_2.setText(_translate("Frame", "选择文件"))
        self.SubtitleLabel_7.setText(_translate("Frame", "APK信息(拖入文件)"))
        self.TitleLabel_2.setText(_translate("Frame", "安装APK"))
        self.SubtitleLabel_3.setText(_translate("Frame", "APK路径"))
        self.PushButton.setText(_translate("Frame", "选择文件"))
        self.PrimaryPushButton.setText(_translate("Frame", "启动安装"))
from qfluentwidgets import ElevatedCardWidget, IconWidget, IndeterminateProgressBar, LineEdit, PlainTextEdit, PrimaryPushButton, PushButton, SimpleCardWidget, SubtitleLabel, TitleLabel
import main_rc
