# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_RestartADB.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 113)
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setGeometry(QtCore.QRect(60, 10, 301, 71))
        self.TitleLabel.setObjectName("TitleLabel")
        self.IndeterminateProgressBar = IndeterminateProgressBar(Form)
        self.IndeterminateProgressBar.setGeometry(QtCore.QRect(20, 80, 361, 4))
        self.IndeterminateProgressBar.setObjectName("IndeterminateProgressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "正在重启ADB服务器"))
from qfluentwidgets import IndeterminateProgressBar, TitleLabel
